CC=g++
CFLAGS=-Wall
LIBS=-lGL -lGLEW `sdl-config --libs`
OBJS=actor.o player.o gamestate.o gamestate_game.o

all: castleinthedungeon
	
castleinthedungeon: main.cpp $(OBJS)
	$(CC) $(CFLAGS) -o castleinthedungeon main.cpp $(OBJS) $(LIBS)

%.o : %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f castleinthedungeon $(OBJS)
